### ISSUE TITLE
您好，test生成的bmp文件错误

### ISSUE THREAD

**Issue by pgr2015** [latelee/yuv2rgb#1]
您好，我将您的代码编译完成，跑测试代码将yuv文件转换成为bmp文件后，bmp文件错误无法打开。
我的环境为ubuntu 16.04
编译器为 g++ 5.4.0
麻烦您回复一下，谢谢

**Comment by latelee** [comment]
> 您好，我将您的代码编译完成，跑测试代码将yuv文件转换成为bmp文件后，bmp文件错误无法打开。
> 我的环境为ubuntu 16.04
> 编译器为 g++ 5.4.0
> 麻烦您回复一下，谢谢

当时我在windows自测通过。你有分析过bmp的内容吗？图片属性字段不正确，会无法打开文件。

**Comment by pgr2015** [comment]
错误信息为，BMP image has unsupported header size。好像就是您说的图片属性字段不正确，请问该怎么修改呢？

**Comment by Rani-Zz** [comment]
ubuntu 18.04 gcc -I. main.cpp -o main 为什么还是会提示头文件中的函数未定义，-I.不是说明头文件目录是当前目录了吗

**Comment by latelee** [comment]
> ubuntu 18.04 gcc -I. main.cpp -o main 为什么还是会提示头文件中的函数未定义，-I.不是说明头文件目录是当前目录了吗

cpp文件用g++来编译。另外，工程涉及到c、c++文件，要分别编译，最后再链接。可用Makefile来操作。

**Comment by Rani-Zz** [comment]
> BMP image has unsupported header size

您好，这个问题我也遇到了，请问最后怎么解决的

**Comment by Rani-Zz** [comment]
> > ubuntu 18.04 gcc -I. main.cpp -o main 为什么还是会提示头文件中的函数未定义，-I.不是说明头文件目录是当前目录了吗
> 
> cpp文件用g++来编译。另外，工程涉及到c、c++文件，要分别编译，最后再链接。可用Makefile来操作。

我执行完了，但是出现了跟跟楼上同样的问题BMP image has unsupported header size

**Comment by latelee** [comment]
我没有在linux下测试过。抽空试试。

**Comment by Rani-Zz** [comment]
> 我没有在linux下测试过。抽空试试。

应该是bmp文件头信息结构体字节对齐的问题,但我还不知道到怎么改

**Comment by latelee** [comment]
> > 我没有在linux下测试过。抽空试试。
> 
> 应该是bmp文件头信息结构体字节对齐的问题,但我还不知道到怎么改

经查，是结构体大小的问题。在32位系统上程序无问题，但在64位上会出现问题。因为unsigned long在64位系统上8字节。当时测试没有充分（大约7年前写的了）。你可以自己修正，我也提交代码了。
