### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oliv3** [latelee/yuv2rgb#3]
Hi, I'd like to test/use `rgb2yuv.[ch]` in my project but it lacks a license. Can you please add one ? Thanks !

**Comment by latelee** [comment]
Hi!
The original code comes from **Project Mayo**, I only change a few for my code style, pls see the license there.
As the code written myself in this project (or in my github), you can use any code in any purpose.

**Comment by oliv3** [comment]
Without a license I can't use it (see [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license) and [here](https://www.quora.com/What-if-I-dont-include-a-license-in-my-public-GitHub-project-Can-people-do-anything-with-my-code?share=1)). I can't find a repository for Project Mayo, would you have some link(s) ? Thanks !

**Comment by latelee** [comment]
I add BSD license file.
I got the file `rgb2yuv.c`  from the internet long long time ago, it  has the following state:
```
/**************************************************************************
 *
 *  rgb2yuv.c, 24-bit RGB bitmap to YUV converter
 *
 *  Copyright (C) 2001  Project Mayo
 *
 *  Adam Li
 *
 *  DivX Advance Research Center <darc@projectmayo.com>
 *
 **************************************************************************/
```
but the website [http://www.projectmayo.com/opendivx/license.php](http://www.projectmayo.com/opendivx/license.php) is not available now. 
I found this [https://www.divx.com/licensing/](https://www.divx.com/licensing/).

**Comment by oliv3** [comment]
Many thanks !
